[package]
name = "tq-launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
dirs = "5.0.1"
octocrab = "0.38.0"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }

